-- seg_ch_1024
CREATE TABLE uav_search.seg_ch_1024\n(\n    `segment_id` String,\n    `dataset_id` LowCardinality(String),\n    `video_id` String,\n    `t_start` Float32,\n    `t_end` Float32,\n    `altitude_m` Float32,\n    `velocity_mps` Float32,\n    `gimbal_pitch` Float32,\n    `person_count` UInt16,\n    `vehicle_count` UInt16,\n    `is_night` UInt8,\n    `embedding` Array(Float32) CODEC(NONE),\n    INDEX idx_vec embedding TYPE vector_similarity(\'hnsw\', \'cosineDistance\', 1024) GRANULARITY 100000000,\n    INDEX idx_alt altitude_m TYPE minmax GRANULARITY 4,\n    INDEX idx_vel velocity_mps TYPE minmax GRANULARITY 4,\n    INDEX idx_per person_count TYPE minmax GRANULARITY 4\n)\nENGINE = MergeTree\nORDER BY (dataset_id, video_id, t_start)\nSETTINGS index_granularity = 8192;

-- seg_ch_2048
CREATE TABLE uav_search.seg_ch_2048\n(\n    `segment_id` String,\n    `dataset_id` LowCardinality(String),\n    `video_id` String,\n    `t_start` Float32,\n    `t_end` Float32,\n    `altitude_m` Float32,\n    `velocity_mps` Float32,\n    `gimbal_pitch` Float32,\n    `person_count` UInt16,\n    `vehicle_count` UInt16,\n    `is_night` UInt8,\n    `embedding` Array(Float32) CODEC(NONE),\n    INDEX idx_vec embedding TYPE vector_similarity(\'hnsw\', \'cosineDistance\', 2048) GRANULARITY 100000000,\n    INDEX idx_alt altitude_m TYPE minmax GRANULARITY 4,\n    INDEX idx_vel velocity_mps TYPE minmax GRANULARITY 4,\n    INDEX idx_per person_count TYPE minmax GRANULARITY 4\n)\nENGINE = MergeTree\nORDER BY (dataset_id, video_id, t_start)\nSETTINGS index_granularity = 8192;

-- seg_ch_256
CREATE TABLE uav_search.seg_ch_256\n(\n    `segment_id` String,\n    `dataset_id` LowCardinality(String),\n    `video_id` String,\n    `t_start` Float32,\n    `t_end` Float32,\n    `altitude_m` Float32,\n    `velocity_mps` Float32,\n    `gimbal_pitch` Float32,\n    `person_count` UInt16,\n    `vehicle_count` UInt16,\n    `is_night` UInt8,\n    `embedding` Array(Float32) CODEC(NONE),\n    INDEX idx_vec embedding TYPE vector_similarity(\'hnsw\', \'cosineDistance\', 256) GRANULARITY 100000000,\n    INDEX idx_alt altitude_m TYPE minmax GRANULARITY 4,\n    INDEX idx_vel velocity_mps TYPE minmax GRANULARITY 4,\n    INDEX idx_per person_count TYPE minmax GRANULARITY 4\n)\nENGINE = MergeTree\nORDER BY (dataset_id, video_id, t_start)\nSETTINGS index_granularity = 8192;

-- seg_ch_512
CREATE TABLE uav_search.seg_ch_512\n(\n    `segment_id` String,\n    `dataset_id` LowCardinality(String),\n    `video_id` String,\n    `t_start` Float32,\n    `t_end` Float32,\n    `altitude_m` Float32,\n    `velocity_mps` Float32,\n    `gimbal_pitch` Float32,\n    `person_count` UInt16,\n    `vehicle_count` UInt16,\n    `is_night` UInt8,\n    `embedding` Array(Float32) CODEC(NONE),\n    INDEX idx_vec embedding TYPE vector_similarity(\'hnsw\', \'cosineDistance\', 512) GRANULARITY 100000000,\n    INDEX idx_alt altitude_m TYPE minmax GRANULARITY 4,\n    INDEX idx_vel velocity_mps TYPE minmax GRANULARITY 4,\n    INDEX idx_per person_count TYPE minmax GRANULARITY 4\n)\nENGINE = MergeTree\nORDER BY (dataset_id, video_id, t_start)\nSETTINGS index_granularity = 8192;

-- telemetry_raw
CREATE TABLE uav_search.telemetry_raw\n(\n    `dataset_id` LowCardinality(String),\n    `video_id` String,\n    `frame_index` UInt32,\n    `timestamp` DateTime64(6),\n    `latitude` Nullable(Float64),\n    `longitude` Nullable(Float64),\n    `altitude_m` Nullable(Float32),\n    `velocity_mps` Nullable(Float32),\n    `gimbal_pitch` Nullable(Float32),\n    `compass_heading` Nullable(Float32),\n    `gimbal_heading` Nullable(Float32),\n    `extra` Map(String, Float64)\n)\nENGINE = MergeTree\nORDER BY (dataset_id, video_id, frame_index)\nSETTINGS index_granularity = 8192;
